version: '3.8'

services:
  # Keycloak server
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8083:8080"
    depends_on:
      - postgres

  # PostgreSQL database
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: loan_user
      POSTGRES_PASSWORD: loan_pass
      POSTGRES_DB: loan_db
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # pgAdmin UI
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@loan.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
